name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
<<<<<<< HEAD
  build:
    runs-on: ubuntu-latest

=======
  build-and-deploy:
    runs-on: ubuntu-latest
>>>>>>> beac5341c82d6a89e8d6bde1ee5b7b3b51a46c32
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

<<<<<<< HEAD
      - name: Install dependencies
        run: bundle install

=======
>>>>>>> beac5341c82d6a89e8d6bde1ee5b7b3b51a46c32
      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
<<<<<<< HEAD
=======
          force_orphan: true
>>>>>>> beac5341c82d6a89e8d6bde1ee5b7b3b51a46c32
